name: node_http
description: HTTP client powered by Node.js I/O system.
version: 1.0.0-dev.8.0
homepage: https://github.com/pulyaevskiy/node-interop
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  http:
    git: https://github.com/dart-lang/http.git
  node_interop: ^1.0.0-dev
  node_io: ^1.0.0-dev

dev_dependencies:
  test: ^1.0.0
  build_runner: ^0.9.0
  build_node_compilers: ^0.1.8
  build_test:

dependency_overrides:
  http:
    git: https://github.com/dart-lang/http.git